name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          # هذا المتغير يخبر buildozer أننا نتحمل مسؤولية العمل بصلاحية root
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          pip install --upgrade buildozer cython
          # هذا الأمر يقوم بضغط y تلقائياً عند طلب التأكيد
          printf "y\n" | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
