name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade buildozer cython
          
      - name: Fix SDK Path
        run: |
          # إنشاء المجلدات المطلوبة
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          
          # تحميل أداة commandlinetools الحديثة من جوجل
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools
          
          # إعادة تسمية المجلد ليتوافق مع ما يبحث عنه النظام
          mv ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          
          # إنشاء رابط رمزي (Symbolic Link) لخداع النظام القديم
          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          
      - name: Build APK
        env:
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          buildozer --verbose android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
